### ISSUE TITLE
Align the form and the list

### ISSUE THREAD

**Issue by emaggy** [fac18/week2-ajnp-sbs-todolist#45]
Design would look neater if the to do input form and the list of to-dos we aligned. Also ensure that the buttons are aligned

![image](https://user-images.githubusercontent.com/40627253/68466897-2feb4680-020d-11ea-873e-26d3ac2715b4.png)

**Comment by sleepysnapdragon** [comment]
Thanks for the comment!  We discussed it and in the end we're going to keep it how it is, ~~because we're lazy~~ just to break up the shape of the content on the page a bit :)
