### ISSUE TITLE
Bear header image 

### ISSUE THREAD

**Issue by jc2820** [fac18/week2-ajnp-sbs-todolist#50]
This may not be a bother at all as it still looks fun as it is, but the header image crops through the bear's face in my browser.

It may be possible to centralise the image in its container based on scale - and get more of that bear onscreen!

But then also it looks like the bear is peeking over the top which is nice :)

**Comment by sleepysnapdragon** [comment]
Thank you! We tried out your suggested edit and it definitely improves the bear position at certain sceensizes, but unfortunately it ends up cutting off the top of the bear's face in other screensizes.  Of the 2 versions we prefer the current one so we're going to leave it how it is.  I guess we should have thought harder about this when planning the responsiveness at the beginning.
