### ISSUE TITLE
Great readme !!!

### ISSUE THREAD

**Issue by frannyfra** [fac18/week2-ajnp-sbs-todolist#51]
I particularly like your readme! Well done team!!

 ![](https://media.giphy.com/media/JRnETNGfx3wlraxFq6/giphy.gif)

It is clear, easy to read, follow and understand.

Good to split it into different parts:

1. stop-continue-go it is a great idea and it is gonna give you a track of your learning process too;

2.How- What- How : will help you to remember the goal of the project in the future.

Keep going on with those great readme 👍

**Comment by renatajarmova** [comment]
Well done!! Keep it up with the great README files 👍
